import { FC, ReactNode, JSX } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./providers";

export const metadata = {
  title: "Next Social App",
  description: "Generated by create next app",
};

interface ILayoutProps {
  children: ReactNode;
}

const RootLayout: FC<ILayoutProps> = ({ children }): JSX.Element => {
  return (
    <html lang="en">
      <body style={{ height: "100vh" }}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
